### ISSUE TITLE
Bitcode support

### ISSUE THREAD

**Issue by loretoparisi** [spotify/ios-sdk#445] opened 2015-09-11 09:10 UTC
For apps that are going to fully implement the "App thinning" of iOS9, the ```Spotify.framework``` should be built with the Build Settings ```Enabled Bitcode``` on or it could have two static libraries one with the Bitcode enabled (that is enabled by default in XCode 7 btw).

**Comment by mhuusko5** [comment] 2015-10-02 14:21
+1 very important

**Comment by AvdLee** [comment] 2015-10-11 17:36
+1, need this to!

**Comment by bassntweeter** [comment] 2015-10-12 11:02
We will release a new beta version of the SDK today which will have Bitcode enabled.

**Comment by mhuusko5** [comment] 2015-10-12 14:10
Tested the new build from today: `'spotify_embedded.c.o' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64`

**Comment by loretoparisi** [comment] 2015-10-12 14:56
```shell
macbookproloreto:ios-sdk admin$ otool -l Spotify.framework/Versions/Current/Spotify | grep bitcode
macbookproloreto:ios-sdk admin$ otool -l Spotify.framework/Versions/Current/Spotify | grep __LLVM
```

confirmed!

**Comment by GabeJacobs** [comment] 2015-10-12 20:12
Also getting the error @mhuusko5 mentioned

**Comment by loretoparisi** [comment] 2015-10-13 15:32
@bassntweeter just to be sure, is the static library compiled with ```-fembed-bitcode``` in the  ```Other C Flags```?
I'm asking, since I see a little of confusion about how it works, which improvements this has in terms of compiled code, etc.
Here there is a good summary about 3rdParty static libraries and Bitcode support:
https://forums.developer.apple.com/thread/3971

**Comment by bassntweeter** [comment] 2015-10-14 07:53
@mhuusko5  @loretoparisi  Thanks for aiding us with testing and thanks for providing valuable feedback. I will dig deeper into this and update with a new release.

**Comment by bassntweeter** [comment] 2015-10-14 08:55
After venturing deeper into this we have determined that this will not be on the top of our priority list at the moment. Some components of the SDK needs to be upgraded to a more recent version to be supported, and that code has not been thoroughly tested yet. Unfortunately you will have to wait for bitcode support and I can not tell you when we will ship it.

**Comment by loretoparisi** [comment] 2015-10-14 09:47
@bassntweeter I guess this is a very common situation, most of the 3rdParty libraries are not "bitcode" ready at this time. Thank you.

**Comment by GabeJacobs** [comment] 2015-10-14 15:26
@bassntweeter agreed, this shouldn't really be a priority. In-app authentication is the biggest request for us. Just takes a real long time for our on boarding process for people to have to remember their login info. Also a web-api would change everything for us, but I assume you are not part of that team?

**Comment by jeffb6688** [comment] 2015-10-19 23:04
@loretoparisi So how do you turn off the linker error. I tried to do this by going to build settings, searching for bitcode, and switching it to NO. But I still get the linker error. What else do I need to do? My specific error is: Spotify.framework/Spotify(SPTAlbum.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by bassntweeter** [comment] 2015-10-21 21:34
@loretoparisi @gabejacobs thanks for your patience and understanding guys.

**Comment by bassntweeter** [comment] 2015-10-21 21:39
@gabejacobs In-app authentication will ship within a couple of weeks. Could you elaborate more on the web-api?

**Comment by GabeJacobs** [comment] 2015-10-21 22:59
@bassntweeter Awesome, thanks so much for that.

Sure. I can explain over email if you would like? My email is gabe@cymbal.fm

**Comment by skagedal** [comment] 2015-10-22 07:18
@bassntweeter Where can I read more about upcoming changes in in-app
authentication?
tors 22 okt. 2015 kl. 00:59 skrev Gabe Jacobs <notifications@github.com>:

**Comment by bassntweeter** [comment] 2015-10-22 15:23
@skagedal We will publish new documentation when we release the Sdk with support for in-app authentication. Basically the Sdk will check if the app is installed and if so take care of authentication in the Spotify app. That way users will not have to login in the web view. This feature was prematurely released in beta 8 if you would like to test a broken version of it. However the place where you white list your application was not on our web at that time, so the feature ended up breaking lots of stuff.

**Comment by bassntweeter** [comment] 2015-10-22 15:29
@gabejacobs I have a rule to not share my email online. However, I must assume that you are aware of https://developer.spotify.com/web-api/ and that you would like to get raw access to the pcm-files.

**Comment by GabeJacobs** [comment] 2015-10-22 15:36
@bassntweeter No problem, understandable of course. What do you mean though about the pcm-files? I'm part of Cymbal (small music startup http://cymbal.fm) and we are currently developing our web application. We've been doing it without full stream playback, hoping that we might be able to soon beta-test a full-stream capable web API. We currently only play the 30 second previews and link out to play on Spotify, but this kind of kills what makes the app so wonderful. So I guess I was wondering if there was any news about the web-api / if Spotify was interested in beta-testers in order to find bugs, develop features, etc.

**Comment by bassntweeter** [comment] 2015-10-22 15:42
@gabejacobs yes that is what I mean. I cannot disclose anything regarding that, however that is a request we have from several other parties.

**Comment by GabeJacobs** [comment] 2015-10-22 15:44
@bassntweeter sounds good, I understand. What do you mean about the pcm-files though? Also do you know how bop.fm does full stream playback?

**Comment by loretoparisi** [comment] 2015-10-22 16:02
@GabeJacobs bop.fm controls the Spotify Desktop app player through a custom protocol.

**Comment by GabeJacobs** [comment] 2015-10-22 16:03
@loretoparisi @bassntweeter sorry we are getting a little off-topic from bitcode... but any idea how they do that?

**Comment by loretoparisi** [comment] 2015-10-22 16:11
@GabeJacobs yes I think here it's too off topic, let's keep this discussion about ```bitcode``` feature request. The latter is about the ```Spotify Play Button``` here https://developer.spotify.com/technologies/widgets/spotify-play-button/, 
But you shouldn't no hack this I mean it's something you have to ask Spotify to control the player. At this time the official doc is the AppleScript doc (https://developer.spotify.com/applescript-api/).

**Comment by loretoparisi** [comment] 2015-11-09 23:06
@bassntweeter the Beta Release 12 does not fully support ```bitcode```. 
So what happens when compiling the ```SpotifySDK.framework``` with an app having bitcode enabled (that since XCode7.1 is by defaults) there is a compilation error:

```shell
ld: bitcode bundle could not be generated because app was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture arm64
```

Is possibile to have a schedule to have full ```bitcode``` support in a next Beta release?
Thank you.

**Comment by iGGNoRe** [comment] 2015-11-15 21:43
@GabeJacobs for in-app Auth do you mean something [like this?](https://github.com/iGGNoRe/SFVC-Spotify-Login)

**Comment by GabeJacobs** [comment] 2015-11-16 15:42
@iGGNoRe I don't think this really solves the issue. The issue is that if a user is logged into Spotify, they should not have to login again and remember their credentials. They should just give access and it should work. This can be done if the SDK gets access to the keychain. It could be based off Soundclouds  SDK which does does this really well.

It just becomes a real problem when Spotify Login is involved in Onoarding. So for us, users sign up for our app, go through one or two pages and then are prompted to login to Spotify. We lose users because the authentication process is long. It should just "work" and people expect it to be very fast especially if they already are logged in via the Spotify app. 

Does that make sense?

**Comment by iGGNoRe** [comment] 2015-11-16 19:56
@GabeJacobs Ah so you're saying more of a Google apps type of setup where even after installing a brand new app, i.e. Drive, it already shows you your accounts that are logged in on the other apps, i.e. Gmail? So the user would basically just be presented with an "Allow Access" button, or something similar, after a query to the Spotify app/storage itself?

**Comment by GabeJacobs** [comment] 2015-11-16 20:01
@iGGNoRe Yeah drive does a great job of this. Do you think they also use keychain accees?

**Comment by JMSerruya** [comment] 2015-12-11 10:18
Bitcode is now available in beta-14!

https://github.com/spotify/ios-sdk/releases/tag/beta-14

**Comment by loretoparisi** [comment] 2015-12-11 10:25
@JMSerruya @bassntweeter Thank you guys! I confirm that the LLVM segments are there:

```shell
macbookproloreto:ios-sdk admin$ otool -l Spotify.framework/Spotify | grep __LLVM
   segname __LLVM
   segname __LLVM
   segname __LLVM
   segname __LLVM
   segname __LLVM
   segname __LLVM
```

:+1:

**Comment by GabeJacobs** [comment] 2015-12-14 15:46
@loretoparisi when I try to archive I get

    ld: bitcode bundle could not be generated because '/Users/gabejacobs/Desktop/Anthem-iOS/Anthem/Spotify/Spotify.framework/Spotify(SPTAudioStreamingController.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7

You don't get that?

**Comment by loretoparisi** [comment] 2015-12-14 18:37
@GabeJacobs missed didn't try this phase already.

**Comment by GabeJacobs** [comment] 2015-12-14 19:04
@loretoparisi what do you mean?

**Comment by loretoparisi** [comment] 2015-12-15 09:42
@GabeJacobs I did not try to archive the binary with ENABLE_BITCODE and fembed_bitcode enabled. I have checked the llvm segments so the build is bitcode for sure. I will check it out.

**Comment by marcshilling** [comment] 2015-12-16 23:41
Same issue as @GabeJacobs -- can't archive

**Comment by JMSerruya** [comment] 2015-12-17 02:10
@marcshilling @gacejacobs Thank you, i'll try to reproduce this and send a fix.

**Comment by cloudjanak** [comment] 2015-12-17 05:18
untill you send a fix , this issue must remain open

**Comment by marcshilling** [comment] 2015-12-30 15:24
Any update on this? Trying to push an app to the store this week.

**Comment by dhint4** [comment] 2016-02-03 17:59
+1 on this. Really need bit code support enabled

**Comment by GabeJacobs** [comment] 2016-02-17 13:11
Is someone able to quickly explain why enabling bitcode is so important?

**Comment by marcshilling** [comment] 2016-02-17 13:46
@gabejacobs https://developer.apple.com/library/tvos/documentation/IDEs/Conceptual/AppDistributionGuide/AppThinning/AppThinning.html

**Comment by iGranDav** [comment] 2016-02-17 13:51
One interesting part is also 

> For watchOS and tvOS apps, bitcode is required.

**Comment by loretoparisi** [comment] 2016-02-18 17:47
@iGranDav Absolutely! You need for both `tvOS` and `watchOS` as well as iOS9 only apps for `iOS`. You can have a look at what happened to `ld` linker before and after tvos support requirements (when it compiled and I was able to run the `Spotify.framework` on tvOS...) https://github.com/spotify/ios-sdk/issues/443

**Comment by jsanders67** [comment] 2016-02-24 02:54
+1 on @GabeJacobs issue

**Comment by nathanandersen** [comment] 2016-03-24 17:29
+1

**Comment by zackfletch00** [comment] 2016-03-27 05:55
+1

**Comment by virenenskully** [comment] 2016-03-27 06:40
+1

**Comment by JMSerruya** [comment] 2016-04-21 11:34
Hello!, this has been fixed in beta-16! Thanks for your patience and feel free to leave a comment if you've any further problems with bitcode!
https://github.com/spotify/ios-sdk/releases/tag/beta-16

**Closed by JMSerruya** 2016-04-21 11:34 UTC

**Comment by marcshilling** [comment] 2016-04-22 13:48
Thanks @JMSerruya! Can confirm I was able to archive with the new beta!
