### ISSUE TITLE
App rejected because of Spotify login screen

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#242] opened 2015-02-03 19:39 UTC
My third (!) update of my app with support for Spotify suddenly got rejected.

From Apple
11.13 - Apps that link to external mechanisms for purchases or subscriptions to be used in the App, such as a "buy" button that goes to a web site to purchase a digital book, will be rejected

11.13 Details
Your app includes an account registration feature, which is considered an access to external mechanisms for purchases or subscriptions to be used in the app. Specifically, your app facilitates Spotify sign up, which can then be upgraded to a paid, premium membership outside of the app. This feature does not comply with the App Store Review Guidelines.

/////////

Does the Spotify SDK provide some other way for a user to login?
If not, I hope you make that possible in a future update of the SDK 
else {
 iOS+Spotify == false;
}

**Comment by Zwaaan** [comment] 2015-02-04 15:26
This is a duplicate of #198. Apple wants you to use an webView but not sure thats compliant with Spotifys rules :S However, Spotify says an update is on the way.

**Comment by iKenndac** [comment] 2015-02-04 15:29
This is _not_ a duplicate of #198. We're working on fixing it, all the same.

**Comment by gbrickley** [comment] 2015-02-06 16:02
@iKenndac is there a timeline for the update?  As of right now, when I use a webView in my app, I can't get the authCallback block to be called after the user logs in.  Any tips you can give on that?

**Comment by iKenndac** [comment] 2015-02-09 09:33
No timeline, but soon. This issue has nothing to do with WebViews - please see #198 for discussion.

**Comment by kennylovrin** [comment] 2015-02-17 14:37
This happened to us as well yesterday, Apple specifically mentioned that it is possible to navigate all the way via the privacy policy link.

**Comment by CVertex** [comment] 2015-02-22 22:46
We got rejected too, but after switching the experience to in-app using UIWebView Apple accepted it. 

We only allow Premium users, and there are still problems with this experience I am investigating. I don't think I'm logging out properly..

**Comment by jayceecam** [comment] 2015-02-26 14:47
Also just got rejected for this reason. Hope Spotify makes a SSO option available very soon.

**Comment by possan** [comment] 2015-03-02 14:50
Sorry for this taking so long, but we're on this and we're trying to get a solution out this week that will use UIWebViews initially, but eventually will support SSO when we get that support in...

**Comment by possan** [comment] 2015-03-04 17:25
We just sent out a new version, which should fix this issue, it would be great if you could confirm that it's fixed.

**Comment by shichongrui** [comment] 2015-03-06 04:56
This doesn't work in the simulator if you try to login with your facebook account. And for those of us that initially created our accounts with facebook and have no spotify username now cannot use it while developing on the simulator.

**Comment by possan** [comment] 2015-03-06 10:32
I just tried to sign in through Facebook in the simulators' web view, it worked fine for me, what's happening for you?

**Comment by kennylovrin** [comment] 2015-03-06 10:47
I have just moved from our custom web view to the new SPTAuthViewController, and it works nicely.

However, does this mean that I don't have to do the whole open url dance at all anymore? I get the feeling that I can basically remove the callback url scheme from my app as it seems it is now handles internally in the auth view controller?

**Comment by shichongrui** [comment] 2015-03-06 15:52
When I click on the Login with Facebook button I get a message in the Xcode console that says (with some stuff removed)

Unknown result for URL https://www.facebook.com/dialog/oauth?client_id=[ClientId]&state=AQC0IrJL5oCdfE797v8I-fdPOJ-cRTI67HhBAP-MnnaReVvoMq58U6rMXpT7G5ltIgnbTJto5JqHWC4WXA&redirect_uri=https%3A%2F%2Faccounts.spotify.com%2Fapi%2Ffacebook%2Foauth%2Faccess_token, for frame <WebFrame: 0x7fb301c835e0>

I am on Xcode Beta 6.3 running Swift 1.2 (using bridging headers) and IOS 8.3 on the simulator.  We have had to put in a temporary button that continues to take us out to Safari so that we can still log in with Facebook.

**Comment by possan** [comment] 2015-04-13 14:44
The SPTAuthViewController uses the URI scheme internally to handle the actual response so you'd still need that.

I'm closing this, re-open if this is still an issue.

**Closed by possan** 2015-04-13 14:44 UTC
Labels: planned-for-next-release

**Comment by NathanWalker** [comment] 2016-04-12 18:38
@possan which version contains the SPTAuthViewController?
this one: https://github.com/spotify/ios-sdk/releases/tag/beta-14

Looks like latest release but posted on Nov. 27?  that wouldn't have it I don't think.
