### ISSUE TITLE
skipPrevious will go back to beginning of current track, but never to previous track

### ISSUE THREAD

**Issue by thegreatmichael** [spotify/ios-sdk#250] opened 2015-02-16 22:52 UTC
perhaps this is what @captain-tarace is describing in #217, but i can at least get it to go back to the beginning of the current track, but not to go to the previous. I do not get an error.

**Comment by iKenndac** [comment] 2015-02-17 08:35
Duplicate of #217.

**Closed by iKenndac** 2015-02-17 08:35 UTC
