### ISSUE TITLE
SPTPlaylistSnapshot playlistWithURI: session: callback: crashes with some playlists

### ISSUE THREAD

**Issue by jeffb6688** [spotify/ios-sdk#256] opened 2015-02-26 19:51 UTC
The following public playlist causes [SPTPlaylistSnapshot playlistWithURI: session: callback: ] to crash. Is there a way to validate this playlist and avoid the crash?

spotify:user:spotify:playlist:5N6tzunZi5b54hHvqnO5Iy

Here is the output at the time of the crash. The stack trace is also shown in the image below.
![screen shot 2015-02-26 at 1 49 08 pm](https://cloud.githubusercontent.com/assets/10351267/6400429/75708f64-bdbe-11e4-8704-5bb2fc3b8e5d.png)

    *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull objectForKeyedSubscript:]: unrecognized selector sent to instance 0x196047ba0'
*** First throw call stack:
(0x184cc659c 0x1953c40e4 0x184ccd664 0x184cca418 0x184bceb6c 0x10018da4c 0x10018bac0 0x100189e98 0x1001a7410 0x1001966ac 0x1001901bc 0x1001a7410 0x1001a123c 0x1004f8e30 0x1004f8df0 0x1005059a0 0x100506f18 0x195be52e4 0x195be4fa8)
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by JMPerez** [comment] 2015-02-27 07:16
It seems this has to do with some null values returned in the response for one of the tracks, between the one named Vertigo and the one named Fallin:

```
..., {
      "added_at" : "2009-12-10T14:20:17Z",
      "added_by" : null,
      "track" : {
        ...     
        "id" : "5JmS4ADcvk5a7eUb247lmP",
        "name" : "Vertigo",
        ...
      }
    }, {
      "added_at" : "2009-12-10T14:20:17Z",
      "added_by" : null,
      "track" : null
    }, {
      "added_at" : "2009-12-10T14:20:17Z",
      "added_by" : null,
      "track" : {
        ...
        "name" : "Fallin'",
        "popularity" : 71,
       ...
      }
    }
    ...
```

This should be fixed either in the Web API or in the method parsing the response, to ignore that track.

**Comment by jeffb6688** [comment] 2015-02-27 15:24
So, when do you expect this to be fixed? Will this be an update to the iOS SDK? Or are you saying we need to use the Web API instead?

**Comment by iKenndac** [comment] 2015-02-27 15:26
Duplicate of #219, closing. A fix will be released soon.

**Closed by iKenndac** 2015-02-27 15:26 UTC
