### ISSUE TITLE
streaming controller is bad at detecting switch from wifi to cellular network

### ISSUE THREAD

**Issue by steve-whitney** [spotify/ios-sdk#409] opened 2015-07-30 01:09 UTC
Steps to reproduce:
 1) app using spt ios sdk is connected to WiFi and Cellular network
 2) app is running and is (presumably) connected to WiFi by default
 3) app is told to play back a spotify track, and audio track is playing - all good.
 4) app is put in background by user
 5) user turns off WiFi via iPhone settings (eg, via bottom controller drawer)
     (Real-world use-case for step 5: start streaming at home, get in car, and drive away from home)
 6) some time later [5-30 seconds, eg], app instructs spt ios sdk to play new track
          ==> Expected: next song plays, streamed from Cellular network
          ==> Result: no audio plays.

**Comment by steve-whitney** [comment] 2015-07-30 01:10
i will post proof-of-issue ios/xcode app ASAP.

**Comment by steve-whitney** [comment] 2015-08-18 13:15
proof-of-issue ios/xcode app: https://github.com/steve-whitney/spt-ios-sdk-issue409

**Comment by joaoAvno** [comment] 2015-08-31 15:15
i have the same problem

**Comment by Jackc415** [comment] 2015-09-04 23:33
Does anyone have a solution? I'm having the same problem.

**Comment by timburks** [comment] 2015-09-16 19:56
I'm seeing a similar problem that involves the cellular connection only.

I'm using the Simple Track Playback sample app in the Beta 10 SDK. After using the Control Center to disable WiFi, I start the sample app and play one of the sample tracks. Then I go back to the Control Center, put my device in Airplane mode, and return to the sample app and wait for play to stall when the app runs out of audio data. Then I press the Play/Pause button a few times to simulate a frustrated user. The first time I press, I usually hear a brief bit of audio before play stops again. Then I go back to the Control Center and reenable Airplane mode and return to the app. Play doesn't immediately resume, so I press Play/Pause and observe that nothing happens for a while. But some significant amount of time later, audio starts playing again. The length of this time interval varies but has been 30 seconds or more.

Is this intended behavior? In our production app, we see frequent network outages as our users move in and out of coverage. When they return to coverage, our other network services restart immediately but Spotify often takes a long time to resume playback. We're observing all delegate methods and not seeing anything get called to inform us of what's happening during the time we're waiting for Spotify playback to restart.

(I've made one change to the Simple Track Playback app: I set the SPTAudioStreamingController's diskCache to nil to limit local caching)

**Comment by bassntweeter** [comment] 2015-10-29 12:38
This has been addressed in Beta 12.

**Comment by GabeJacobs** [comment] 2015-11-04 19:44
I'm still getting this issue on Beta 12

**Comment by sajsanghvi** [comment] 2015-11-05 17:41
still getting this issue as well

**Comment by sajsanghvi** [comment] 2015-11-05 17:42
still getting this issue as well

**Comment by bassntweeter** [comment] 2015-11-10 11:12
Ok guys, thanks for helping us test this. We will try to find a better fix for it.

**Comment by GabeJacobs** [comment] 2015-11-10 17:53
thanks @bassntweeter keep us updated. It's specifically bad going from wifi to LTE. I often have to quit out of our app in order to get it to play again,

**Comment by JMSerruya** [comment] 2015-11-23 14:46
@steve-whitney are you still getting this issue in beta-12 ?

@GabeJacobs @sajsanghvi can you provide reproduction steps for your problem?

**Comment by GabeJacobs** [comment] 2015-11-23 15:25
@JMSerruya 

Sure

1) Connect to Wifi
2) Play a Spotify song with wifi

> To do that we call: [SPTTrack trackWithURI] and then [self.spotifyPlayer playURIs]

3) Turn off wifi via command center (wifi goes away, and 5 bars of AT&T LTE shows)

At this point the song will play as much as it has buffered via wifi. Usually it is able to play for about 10 more seconds. Then, every time, it stops. 

There may be other cases, but I'm always able to reproduce it this way.

**Comment by steve-whitney** [comment] 2015-12-04 19:32
@JMSerruya 
sad to say, we abandoned our prototype due to a number of issues, this #409 being one of the few tech issues.

**Comment by GabeJacobs** [comment] 2015-12-04 19:33
@steve-whitney @JMSerruya seems to be fixed with beta 13

**Comment by JMSerruya** [comment] 2015-12-11 10:19
Please retest with beta-14

https://github.com/spotify/ios-sdk/releases/tag/beta-14

**Closed by JMSerruya** 2015-12-11 10:19 UTC

**Comment by GabeJacobs** [comment] 2015-12-14 17:54
@steve-whitney have you been able to test this on beta-14? We are still experiencing problems

**Comment by abrasdev** [comment] 2016-02-25 03:15
+1

**Comment by kraghavan-cc** [comment] 2016-07-22 23:07
I still see this issue happening. The steps are same as what @abrasdev has mentioned.

**Comment by JasonYangGe** [comment] 2016-10-19 09:00
@JMSerruya spotify ios sdk beta 24 version not fixed turn off wifi to change LTE(4G) try to play the song.it won't work.

**Comment by Brockify** [comment] 2017-03-17 23:20
This is still an issue I have found and it really needs to be fixed since it is breaking my application (switching from wifi->lte)

**Comment by sajsanghvi** [comment] 2018-04-11 23:54
still having this issue too
