### ISSUE TITLE
[Bug] Free Users are granted access token when scope is set to SPTAuthStreamingScope

### ISSUE THREAD

**Issue by ardaerzin** [spotify/ios-sdk#644] opened 2016-04-13 01:25 UTC
Hey everyone,

I'm trying to figure out the expected behavior and see if I'm making any mistakes. When I set **SPTAuthStreamingScope** in requested scopes I'm still able to log in with my free account. Is this the expected behavior with the SPTAuthViewController? Also, when I check the **product** property of my user after login to see if the user is premium or not, it is always Unknown. I'm able to perform search requests but havent tried streaming yet.

**Comment by bass4aj** [comment] 2016-04-13 13:32
If this is the case, then chances are there is something wrong with your login. Search requests work without a valid session, so most likely you are providing access to your app despite login giving you an invalid session.

**Comment by ardaerzin** [comment] 2016-04-13 13:49
the way im using login is like this

- I set the requestedScopes, clientId, redirectUrl, swap/refresh urls at the application launch, like this:

`func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
        
        SPTAuth.defaultInstance().requestedScopes = [SPTAuthStreamingScope , SPTAuthUserReadPrivateScope]
        SPTAuth.defaultInstance().clientID = *clientId*
        SPTAuth.defaultInstance().redirectURL = *redirect url*
        
        SPTAuth.defaultInstance().tokenRefreshURL = *refreshurl*
        SPTAuth.defaultInstance().tokenSwapURL = *swapurl*
`

- and then for login I use the following in my view controller:

`
func loginWithSpotify(sender: AnyObject!){
        let loginViewController = SPTAuthViewController.authenticationViewController()
        loginViewController.delegate = self
        loginViewController.modalPresentationStyle = .OverFullScreen
        presentViewController(loginViewController, animated: true, completion: nil)
}
`

after the login func, delegation method `func authenticationViewController(authenticationViewController: SPTAuthViewController!, didLoginWithSession session: SPTSession!) ` is getting called with a session. 

What is wrong with this approach so far?

**Comment by ardaerzin** [comment] 2016-04-13 14:06
I've also tried logging in with `UIApplication.sharedApplication().openURL(SPTAuth.defaultInstance().loginURL)`. In the application delegate I'm using :

    func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
        
        if SPTAuth.defaultInstance().canHandleURL(url) {
            SPTAuth.defaultInstance().handleAuthCallbackWithTriggeredAuthURL(url, callback: { (err, session) in
                if let e = error {
                    print("error with spotify login")
                }
            })
        }
    }

However I get the same result, no matter how I choose to log in

**Comment by ardaerzin** [comment] 2016-04-13 15:57
ok so I just upgraded my account to premium (hell of an acquisition technique btw, well played) and the product is correctly set to Premium after login. That clears the concerns about my login flow. But seriously, what is going on with free users?

**Comment by greencoppercompany** [comment] 2016-04-13 15:57
Hi there! 

We're not doing the same use case described by ardaerzin but we can see that for some premium account we're getting a status of Unknown instead of premium. Not same start, but same end.

This lead to 403 error when we try to reach the me/tracks endpoint.

Can this be related? If not let us know if we need to open another issue.

Thanks.

**Comment by bass4aj** [comment] 2016-04-15 15:57
I tested this just recently. Back when I used Beta 12, logging in with a free account while streaming was requested would deny login. With Beta 14, I get the same result as you. I am working on troubleshooting the same problem that greencoppercompany is mentioning. As far as I know, the only way to handle this right now is to check the user access level and deny them access if it returns as unknown. Its fairly frustrating for my users.

**Comment by bass4aj** [comment] 2016-04-15 15:58
+1

**Comment by greencoppercompany** [comment] 2016-04-20 13:31
Hi folks,

Any news regarding this one?

**Comment by patrickbusch** [comment] 2016-04-25 16:27
Regarding the product property of the user the documentation says this:

"Will be SPTProductUnknown unless your session has been granted the SPTAuthUserReadPrivateScope scope."

**Comment by ardaerzin** [comment] 2016-04-25 18:05
It is not related to SPTAuthUserReadPrivateScope because it is set in my application. The bug is doing exactly what the title says

**Comment by patrickbusch** [comment] 2016-04-25 19:58
was not meant for you but for @greencoppercompany, I just wanted to rule out that possibility just as you said, sorry if that wasn't clear.

**Comment by greencoppercompany** [comment] 2016-04-25 22:14
Sorry for the confusion by stealing your issue @ardaerzin :) I would open a new issue.

**Comment by greencoppercompany** [comment] 2016-05-05 16:12
I can confirm we were using the wrong permission level.

**Comment by erdtman** [comment] 2016-05-19 17:23
So that is by design (the possibility to get an access token with streaming scope for a free user). The  enforcement of streaming right is not done by the token issuance component, but by the streaming components.

I´m closing this issue and if I misunderstood the issue or if you have further information to complement with feel free to reopen the issue.

**Closed by erdtman** 2016-05-19 17:23 UTC
