### ISSUE TITLE
b24 frameworks do not support bitcode while b23 did

### ISSUE THREAD

**Issue by sigalf** [spotify/ios-sdk#786] opened 2016-10-16 09:28 UTC
*If you are filing a bug report, please include information for the topics below. Also, please make sure to only report one bug/feature request/question per issue.*

## Description
b24 frameworks do not support bitcode while b23 did

### Versions
iOS SDK version b24
Spotify app version (if native SSO flow is involved)

### Severity
Major

## Steps to Reproduce
Create a project that supports bitcode and include the 3 spotify frameworks

### Actual behaviour
Impossible to link the project when bitcode is enabled

### Expected behaviour
Expect bitcode to be supported

## Logs
NA

**Comment by DmytroAnkudinov** [comment] 2016-10-17 13:52
We were not able to reproduce the issue. The projects that we created supported the bitcode indeed and successfully used all three frameworks. Our application,  Simple Track Playback Player, builds and runs as well.

Have you been using XCode 7 or earlier? In this case we suggest to upgrade to XCode 8. If you have been using XCode 8, could you please outline steps to reproduce the issue in more detail?

**Comment by marco1981** [comment] 2016-10-17 17:03
@DmytroAnkudinov please try to create an archive on XCode8 using all three framework. It seems bitcode is not supported

**Comment by sigalf** [comment] 2016-10-18 10:00
You must have posted a wrong version of the framework then. compiling the provided Simple Tracks Playback Player gives an eror as well when you archive. see below : ld: bitcode bundle could not be generated because '../../SpotifyMetadata.framework/SpotifyMetadata(SPTJSONDecoding.o)' was built without full bitcode. All object files and libraries for bitcode must be generated from Xcode Archive or Install build for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cameronehrlich** [comment] 2016-10-22 00:28
I too am getting the error saying that I need to enable bitecode for the Spotify framework.  For now I have to disable bitcode app-wide until this is resolved.

**Comment by DmytroAnkudinov** [comment] 2016-10-28 13:21
Fixed in Beta25.

**Closed by DmytroAnkudinov** 2016-10-28 13:21 UTC
Labels: bug, in progress
