### ISSUE TITLE
SPTRequest requestItemAtURI leaks

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#269] opened 2015-03-09 10:49 UTC
Using Beta 7

Add the leakTest method below into the "Simple Track Playback" app:

- (void)leakTest
{
  NSURL *uri = [NSURL   URLWithString:@"spotify:user:cariboutheband:playlist:4Dg0J0ICj9kKTGDyFu0Cv4"];

  SPTAuth *auth = [SPTAuth defaultInstance];
  SPTSession *session = auth.session;

  __block int countItems = 0;

  for (int i = 0; i < 100; i++)
    {
    [SPTRequest requestItemAtURI:uri withSession:session callback:^(NSError *error, id object)
      {
      countItems++;
      NSLog(@"i == %d countItems %d", i, countItems);
      }];
    }

}

Run the “Simple Track Playback” sample app, call the method from say "playPause" and watch the “Memory” symbol in the Xcode “Debug Navigator”,
one can see that the used memory grows all the time.

Sooner or later the app will receive a “didReceiveMemoryWarning” message.
After this the app will crash with an “Terminated due to Memory Error” error.

**Comment by iKenndac** [comment] 2015-03-09 10:51
Duplicate of #199.

**Closed by iKenndac** 2015-03-09 10:51 UTC
