### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by maheshlantech** [spotify/ios-sdk#735] opened 2016-08-25 14:32 UTC
2016-08-25 20:00:27.715 empinfo_11_08[3466:280189] -[ViewController getErrorResponceData:errorCode:fieldType:]: unrecognized selector sent to instance 0x7fe75a4ba380
2016-08-25 20:00:27.719 empinfo_11_08[3466:280189] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[ViewController getErrorResponceData:errorCode:fieldType:]: unrecognized selector sent to instance 0x7fe75a4ba380'
*** First throw call stack:
(
	0   CoreFoundation                      0x00000001037aad85 __exceptionPreprocess + 165
	1   libobjc.A.dylib                     0x000000010321edeb objc_exception_throw + 48
	2   CoreFoundation                      0x00000001037b3d3d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
	3   CoreFoundation                      0x00000001036f9cfa ___forwarding___ + 970
	4   CoreFoundation                      0x00000001036f98a8 _CF_forwarding_prep_0 + 120
	5   empinfo_11_08                       0x0000000102896b36 __46-[CFWebService sendJsonDataRequest:arguments:]_block_invoke.37 + 374
	6   empinfo_11_08                       0x000000010289eb5b __64-[AFHTTPRequestOperation setCompletionBlockWithSuccess:failure:]_block_invoke.45 + 91
	7   libdispatch.dylib                   0x000000010776bd9d _dispatch_call_block_and_release + 12
	8   libdispatch.dylib                   0x000000010778c3eb _dispatch_client_callout + 8
	9   libdispatch.dylib                   0x00000001077741ef _dispatch_main_queue_callback_4CF + 1738
	10  CoreFoundation                      0x00000001037040f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
	11  CoreFoundation                      0x00000001036c5b99 __CFRunLoopRun + 2073
	12  CoreFoundation                      0x00000001036c50f8 CFRunLoopRunSpecific + 488
	13  GraphicsServices                    0x0000000107228ad2 GSEventRunModal + 161
	14  UIKit                               0x00000001044cdf09 UIApplicationMain + 171
	15  empinfo_11_08                       0x0000000102890baf main + 111
	16  libdyld.dylib                       0x00000001077c092d start + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by maheshlantech** [comment] 2016-08-25 14:33
please help me

**Comment by erdtman** [comment] 2016-08-26 05:20
You will have to give a better description of what you are trying to do.
Answer the following questions

- What is the persevered error and when does it occur?
- How do we reproduce the issue, preferable step by step instructions?
- Actual and expected outcome?

And in best case a code example triggers the error

**Comment by erdtman** [comment] 2016-08-29 12:24
Since there has come no new information here I will close this issue.

**Closed by erdtman** 2016-08-29 12:24 UTC
