### ISSUE TITLE
setIsPlaying:YES doesn't resume a track

### ISSUE THREAD

**Issue by kraghavan-cc** [spotify/ios-sdk#671] opened 2016-05-19 23:56 UTC
I use the setIsPlaying:NO in SPTAudioStreamingController to pause the track and setIsPlaying:YES to resume the track. This works very well in good network conditions.

We have Spotify sdk in our iOS app that is often used by users in poor network area and while they drive.

Issue:

When a user is listening to spotify track in my app and when they go to poor network area, after a while (say around 30-40 seconds) the track could not play obviosuly for poor network  conditions.
So I set setIsPlaying:NO and update my UI (button) to indicate the track had paused.

Now within few minutes when the user goes back to good network area and hits resume button again, I call setIsPlaying:YES hoping the track will resume. But most of the times the track won't resume.

This issue can be simulated in the following way:
1. Start your app that has spotify integrated.
2. Start playing a track.
3. Go to iPhone Settings > Developer > Network Link Conditioner > Status> Enable the switch. Then choose 100% loss profile.
4. Move back to your app
5. Let the track play until it can play . Wait till the track pauses.( Do setIsPlaying:NO in your code here)
6. After track pauses, go back to iPhone Settings> Developer> Network Link conditioner> Status> Disable the switch (make sure you change the profile to wifi or something.)
7.  Move back to your app and hit resume button ( Do setIsPlaying:Yes in your code here). See that the track won't resume (most of the times).

NOTE: In step 5, in the code if you decide to stop the track instead of pause, then in step 7, hitting play button will start the track from the beginning. 

This issue is consistent in almost all the spotify versions including the latest version beta 16.

**Comment by kraghavan-cc** [comment] 2016-05-24 21:43
Does anyone  have a clue on this?

**Comment by knagle** [comment] 2016-06-09 17:04
Try investigating currentPlaybackPosition for your SPTAudioStreamingController before resuming the track, then use seekToOffset to start again without calling setIsPlaying:YES
In our app setIsPlaying:YES would always restart the track from the beginning no matter what we tried, so this was the only way to get it back to the position it had been paused in. I was surprised that seekToOffset actually re-started playback, but not as surprised/frustrated that setIsPlaying:YES would constantly restart the track from the beginning.

**Comment by erdtman** [comment] 2016-06-29 11:14
Do you get a NSError in the callback block? If yes what does it say?

**Comment by kraghavan-cc** [comment] 2016-07-20 01:46
I tried @knagle 's approach and it worked only if I use the seekToOffSet within playUri's completion block. seekToOffset doesn't work otherwise.

@erdtman  I will check for the NSError callback block when I do this test again

**Comment by mhuusko5** [comment] 2016-07-20 11:11
@kraghavan-cc There have been many issues related to this – the issue is not setIsPlaying/seekToOffset related, it's network related. The SDK has never been able to handle a network connectivity switch, and renders the player unusable (sometimes stopping it/logging it out then back in, then re-playing track, can fix.. although this is very difficult as of the latest beta, without callback based player login/out).

**Comment by jakereps** [comment] 2016-07-20 16:36
This sounds like it is related to #512, which has been going on forever like @mhuusko5 said.

**Comment by DmytroAnkudinov** [comment] 2016-10-26 11:18
@kraghavan-cc Can you reproduce the issue on the newest version of the API? Lots of functionality have been refactored, including streaming and disk caching. Now, if you have network connection you can resume play/seek to any place of the song, and while network connection is down, you can only let the cached chunk play, while seeking/resuming after pause would not work.

**Comment by DmytroAnkudinov** [comment] 2016-11-04 15:51
No update from issue poster for more than a week. Closing the issue as fixed as functionality pertaining to the issue has been refactored and there are no reports confirming that issue could be reproduced.

If you can reproduce the issue on an iOS SDK Beta 25 or newer, please open a new issue.

**Closed by DmytroAnkudinov** 2016-11-04 15:51 UTC
Labels: bug, playback
