### ISSUE TITLE
Crash in [SPTPlaylistSnapshot playlistWithURI: session: callback: ]

### ISSUE THREAD

**Issue by martinobonfiglioli** [spotify/ios-sdk#210] opened 2015-01-13 11:13 UTC
**Internal method that causes this crash:**

-[SPTPlaylistSnapshot initWithDecodedJSONObject:error:] at /Users/spotify-buildagent/buildAgent/work/f0512cb09316daec/src/SPTPlaylistSnapshot.m:146

**Console Log:**

-[NSNull longValue]: unrecognized selector sent to instance

**Comment by possan** [comment] 2015-01-19 09:50
I can't reproduce it, do you have the uri to the playlist that you're trying to load?

**Comment by martinobonfiglioli** [comment] 2015-01-22 09:42
Nope, it happened one time during loading all my playlists.
BTW hope my detailed debug description can help.

**Comment by possan** [comment] 2015-03-04 17:26
We just sent out a new version, which should fix this issue, it would be great if you could confirm that it's fixed.

**Comment by possan** [comment] 2015-04-13 14:19
I'm closing this, re-open if this is still an issue.

**Closed by possan** 2015-04-13 14:19 UTC
