### ISSUE TITLE
[Bug] Login from Spotify App. Unkown Error

### ISSUE THREAD

**Issue by ardaerzin** [spotify/ios-sdk#650] opened 2016-04-18 14:25 UTC
often I encounter with an unknown error at `handleAuthCallbackWithTriggeredAuthURL`callback after a login attempt from Spotify iOS app.

```
Error Domain=com.spotify.auth Code=0 "unknown_error" UserInfo={NSLocalizedDescription=unknown_error}
```

So far I found the solution in terminating / restarting the spotify app, but this might be a frustrating problem for end users

**Comment by JMSerruya** [comment] 2016-04-19 21:22
Hello!

Which version of the beta are you using?

**Comment by ardaerzin** [comment] 2016-04-19 21:26
I've seen this on 14 & 15

**Comment by GabeJacobs** [comment] 2016-04-19 21:28
Still experiencing this on 15 as well.

**Comment by ardaerzin** [comment] 2016-04-21 08:36
didn't see #505 since it is closed at the moment but I believe it is related

**Comment by GabeJacobs** [comment] 2016-04-21 15:09
Same error

**Comment by samgiagtzoglou** [comment] 2016-04-30 21:51
Also having this issue

**Comment by chrisfarrell** [comment] 2016-05-02 13:47
+1

**Comment by zakmandhro** [comment] 2016-05-03 22:29
+1 problem seems to persist, even in [Beta-16](https://github.com/spotify/ios-sdk/releases/tag/beta-16)

**Comment by GabeJacobs** [comment] 2016-05-03 23:01
+1 getting this error on beta 16 as well

**Comment by GabeJacobs** [comment] 2016-05-03 23:04
@JMSerruya a temporary fix would be to go back to the way beta-12 did it which was just show the webview for authentication. This way we could all upgrade to beta 16 and get things like the runBackround loop fix.

**Comment by Voxar** [comment] 2016-05-10 09:59
Hello @ardaerzin, @GabeJacobs, @samgiagtzoglou, @chrisfarrell, @zakmandhro.

I'm looking into this, trying to reproduce the problem. Any information of circumstances where this problem starts to occur would be very helpful. 

Have you for example noticed the problem occurring more frequently after performing specific operations? Perhaps after spotify has been playing music for a while or mostly after just leaving the device alone for some time with spotify on in the background but not playing music?

Any hints would be helpful to hunt this down. Thank you.

**Comment by ardaerzin** [comment] 2016-05-10 11:50
@Voxar Others may have different observations but it seemed to me that leaving the spotify app open for some time was a probable cause. Don't know exactly but in that case, app switching does somehow feel like happening quite fast but results in an error. Repeating the process doesn't help unless I kill the Spotify app.

**Comment by GabeJacobs** [comment] 2016-05-10 14:22
@Voxar For now I've simply taken the spotify-action field out of info.plist so it just uses the web view. I will keep trying to reproduce though.

**Comment by chrisfarrell** [comment] 2016-06-06 15:24
@Voxar I have the same experience as others. It's intermittent. I am at a stage of development where I am not yet streaming anything. I am using beta-16. I usually see the error after deleting the app off my phone and then re-running, without killing the Spotify app. So, during dev I will hit the Spotify auth screen and it will work fine - then at some point I will delete the app and re-run - this is when I see the error pretty consistently.

**Comment by chrisfarrell** [comment] 2016-06-06 15:29
@Voxar is it possible for me to force the Safari Web Auth when I get the error? I'd like to keep the app-to-app auth in place and if it fails send the user to Safari.

**Comment by GabeJacobs** [comment] 2016-06-06 16:21
@chrisfarrell yeah you could do this. If you get the unknown error, you could pull up the SPTAuthController. I thought about doing this, but I thought the flow would be strange for the user. Go out of the app -> come back -> pull up the webview.

**Comment by dtrenz** [comment] 2016-06-12 17:42
Also experiencing this same issue.

**Comment by christopherpow** [comment] 2016-06-15 02:53
I'm also experiencing this on beta-16.

**Comment by dtrenz** [comment] 2016-06-20 15:00
I'm now seeing this on 1 in 3 inter-app auth attempts. In other words, this makes the entire inter-app auth feature of this SDK un-shippable. Please prioritize this critical bug.

**Comment by gtokman** [comment] 2016-06-25 17:25
Any fix for this issue? 

I am using the beta-16 and keep getting an "unkown_error".

```

import UIKit

@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {
	var window: UIWindow?
	var getSession: (SPTSession -> Void)?

	func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool {
		// Override point for customization after application launch.
		return true
	}

	func application(application: UIApplication, openURL url: NSURL, sourceApplication: String?, annotation: AnyObject) -> Bool {
		// Handle callback
		let auth = SPTAuth.defaultInstance()

		guard auth.canHandleURL(url) else { print("Error"); return false }

		auth.handleAuthCallbackWithTriggeredAuthURL(url) { (error, session) in
			// Guard error
			guard error == nil else { return } // <------------------ "Unkown error"

			// Success
			print("Success: \(session.accessToken)")
			// Capture session
			if let getSession = self.getSession {
				getSession(session)
			}
		}

		return true
	}
```

Console log
<img width="434" alt="screen shot 2016-06-25 at 1 23 18 pm" src="https://cloud.githubusercontent.com/assets/12258850/16358121/3df4c5d0-3ad8-11e6-9658-568b4182802f.png">

**Comment by GabeJacobs** [comment] 2016-07-07 16:56
Beta 17 still has this issue :(

**Comment by erdtman** [comment] 2016-07-08 16:09
What scopes are you requesting?

**Comment by dtrenz** [comment] 2016-07-08 21:30
I'm requesting `SPTAuthStreamingScope`

**Comment by GabeJacobs** [comment] 2016-07-13 15:23
@erdtman This is a major issue for us and we can't upgrade the beta because users cannot login reliably. Please help.

**Comment by philiparpin** [comment] 2016-07-18 01:10
I am also having this exact same issue

**Comment by NOlivNeto** [comment] 2016-07-21 18:57
+1 Three months later and I still face this issue. Could we help with something? This is really serious.

**Comment by philiparpin** [comment] 2016-08-02 23:30
I'm still facing this issue.

**Comment by GabeJacobs** [comment] 2016-08-04 19:39
It's been quite some time since this bug was introduced. It would be a shame to build such a great package for developers to use, only  to leave core issues untouched for months and months. There are only a couple of these really terrible bugs that needs fixing for the SDK to come out of beta. All we can do is encourage the Spotify team, and to express how important it is to us, as a community, that these bugs are patched. Please consider fixing this issue. If there is anything we could do to help, please let us know.

**Comment by GabeJacobs** [comment] 2016-08-17 18:50
Can anyone confirm if this is happening to them on beta 20?

**Comment by d-kunin** [comment] 2016-08-17 18:58
@GabeJacobs that must be fixed on Spotify App side. We are not sure when it might be released on  App Store since we don't know when the next release happens.

Instead you can disable native/SSO login for now, please refer to the change log and the demo.

**Comment by GabeJacobs** [comment] 2016-08-17 18:59
@d-kunin gotcha. I'm trying to recreate the bug on the newest version of spotify. So we'll see I guess?

**Comment by d-kunin** [comment] 2016-08-17 19:41
@GabeJacobs sorry if I was not clear enough. 
The fix is not implemented yet, however we know the reason and working on the fix. So it is not in the current release of Spotify App. It might be in the next release, but we dont know when the next release happens because of the reason partly outside of Spotify.

**Comment by GabeJacobs** [comment] 2016-08-17 19:41
@d-kunin yah, was going to say, just got the error

**Comment by GabeJacobs** [comment] 2016-08-17 22:00
@d-kunin let me know if there is anything I can do to help fix the issue. Still hard for me to reproduce, but once it happens, it happens every time and I can catch it in a breakpoint when the authentication fails

**Comment by skiddle** [comment] 2016-09-19 13:18
+1

We notice this when we present the SPTAuthViewController. It occurs irrespective of scopes. Only seems to occur under the condition

`[SPTAuth defaultInstance] session] == nil`

We login and get an error. However, next time we attempt to login, a valid session is present, so it's obviously working the first time around, just sending a blank error across.

**Comment by bensebborn** [comment] 2016-09-23 14:41
Any movement with Beta 22?

**Comment by erdtman** [comment] 2016-09-24 07:27
No, beta 22 does not solve this issue.

We think we have identified and solved this issue but the issue was in the Spotify App i.e. a release of the SDK cannot solve the issue.

With Apple blocking our releases we cannot say when the fix will be released.

**Comment by motoshima1150** [comment] 2016-09-29 08:27
+1

**Comment by mindgraffiti** [comment] 2016-11-11 19:01
This appears to be fixed as of Beta 25 and Spotify app version 6.8.0. After multiple tests I'm no longer able to reproduce the issue. Can anyone else confirm?

**Comment by erdtman** [comment] 2016-11-11 20:26
Happy to hear that we seem to have made some progress on this, if our hypothesis is correct this is solved by a change in 6.8.0 i.e. no need for beta 25.

If would be awesome if we could get confirmation of this from some more of you.

**Comment by NOlivNeto** [comment] 2016-11-14 13:55
@erdtman Using Beta 23 and app 6.8.0 and works. I think you're correct.

**Comment by hughrawlinson** [comment] 2017-10-28 14:30
Seems like this issue is resolved. If not, please reopen it :)

**Closed by hughrawlinson** 2017-10-28 14:30 UTC
Labels: authentication, bug
