### ISSUE TITLE
VOX app breaking Spotify Auth for all apps

### ISSUE THREAD

**Issue by zakmandhro** [spotify/ios-sdk#869] opened 2017-07-07 00:35 UTC
## Description
The [VOX iOS app](https://itunes.apple.com/us/app/vox-flac-music-player-with-mp3-equalizer/id916215494) is breaking authentication flow in apps that use Spotify Auth. VOX is using Spotify's URL scheme. When Spotify Auth tries to open the Spotify App for authentication, it ends up opening the VOX app instead.

Spotify will have to inform VOX or Apple to get the Spotify URLs removed from the VOX app.

### Severity
Major

## Steps to Reproduce
1. Uninstall Spotify app
2. Install VOX app
3. Authenticate via Spotify Demo app - VOX app will open

### Actual behaviour
`SPTAuthViewController` should open the Spotify native app for authentication.

### Expected behaviour
`SPTAuthViewController` opens the VOX app when attempting to authenticate.

**Comment by hughrawlinson** [comment] 2017-08-16 09:40
Hi @zakmandhro - this issue should be fixed now, please reopen this issue if you experience it again.

**Closed by hughrawlinson** 2017-08-16 09:40 UTC

**Comment by AEDWIP** [comment] 2017-08-16 16:49
Hi Hugh

I really appreciate you looking into this issue. How was this fixed? It does not look like a new version of the sdk has been pushed?

Kind regards

Andy

**Comment by hughrawlinson** [comment] 2017-08-16 22:49
Hey @AEDWIP - this was caused by an issue in the VOX app that has to my understanding now been fixed.
