### ISSUE TITLE
Apple Rejection

### ISSUE THREAD

**Issue by bimusiek** [spotify/ios-sdk#632] opened 2016-03-29 07:45 UTC
Hey, Apple rejected our app because of 

> We noticed that the user is taken to Safari to sign in for a Spotify account, which provides a poor user experience. 

I saw already other issues and I see you implemented `SPTAuthViewController`, so we are changing it now.
I wanted only to suggest to change tutorial https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/#creating-the-application-code so new developers won't have this problem in future.

**Comment by brki** [comment] 2016-03-30 12:11
Interesting, thanks for the heads-up before I submit my app.

I find it a strange reaction on the part of Apple though.  As a security-conscious user who is prompted to log in using some third-party app, I feel more comfortable if it sends me to Safari.  I mean, if it happens in-app, how do I know that the app isn't stealing or storing my password?

**Comment by bimusiek** [comment] 2016-03-30 12:31
@brki I have the same feeling, unfortunately this is our second app that was rejected because of this issue. 

Also, once they complained that we use Spotify logo which is registered trademark, we had to change it to just `UILabel` with `Login to Spotify` ...

**Comment by zackfletch00** [comment] 2016-03-31 18:45
+1, I got rejected for the exact same reason today.  I was only following Spotify's [direct recommendation](https://developer.spotify.com/technologies/spotify-ios-sdk/tutorial/#creating-the-application-code), but apparently Apple has recently changed their guidelines so that this is no longer acceptable.

Apple's note:

> We noticed that the user is taken to Safari to sign in or register for an account, which provides a poor user experience.

**Comment by zackfletch00** [comment] 2016-03-31 19:33
I think this may be a duplicate of [issue 242](https://github.com/spotify/ios-sdk/issues/242).  I should've been more diligent in researching possible rejection reasons before submitting my app (the SDK is still in beta, after all).  Yet, I still feel this issue isn't completely resolved for the future, since the relevant docs have not been updated to include SPTAuthViewController.

**Comment by hughrawlinson** [comment] 2017-10-28 14:29
Hi! The tutorial now explains to use the `authViewController`.

**Closed by hughrawlinson** 2017-10-28 14:29 UTC
Labels: authentication
