### ISSUE TITLE
Massive skipNext performance degradation in Beta 21

### ISSUE THREAD

**Issue by gchilds** [spotify/ios-sdk#746] opened 2016-09-03 03:00 UTC
I've noticed that skipping tracks in Beta 21 feels and is measurably much slower than in Beta 17

NB: letting the track finish and continue onto the next one doesn't seem to have a noticeable delay.

I've modified the Simple Track Playback to show the difference, one branch is B17, the other B21:

https://github.com/gchilds/ios-sdk/tree/beta-17-skip-timing
https://github.com/gchilds/ios-sdk/tree/beta-21-skip-timing

Both samples use track URIs (`playURIs` in beta 17 and `playSpotifyURI` + `queueSpotifyURI` in beta 17),
although skipping when playing the original playlist URI seems to have the same performance problem.  

If you look at the `NSLog` timestamps you can see the time difference between hitting next and the first call to `didStartPlayingTrack`:

e.g. Beta17, 3ms

2016-09-03 11:25:38.163 Simple Track Playback[3832:1590049] START SKIP
2016-09-03 11:25:38.166 Simple Track Playback[3832:1590049] TRACK STARTED PLAYING

e.g. Beta21 1600ms
2016-09-03 11:33:38.055 Simple Track Playback[3847:1593323] START SKIP
2016-09-03 11:33:39.611 Simple Track Playback[3847:1593323] Starting spotify:track:0zFasvRSRxKWrtpGdFqsHS
 
To make it fair for beta 21, I wait until metadata's `nextTrack` has been non-nil for a several seconds, so the SDK has definitely had time to prepare for the skip.

**N.B** I don't know if enabling disk caching would improve performance as it is _currently broken_ (#722)

This performance regression is making our app feel slow and sluggish.

Can you help us out?

**Comment by gchilds** [comment] 2016-09-09 01:53
@fotiDim are you seeing the same thing? Spotify Beta 21 seems much slower than beta 17.

**Comment by CVertex** [comment] 2016-09-09 01:53
@erdtman @d-kunin Have you looked at this issue? This SDK is much slower than the beta 19 and lower. The same is true for seek.

**Comment by erdtman** [comment] 2016-09-12 06:28
Thanks for reporting this, I have reproduced the issue with @gchilds modifications to the example project.

We will see if we can do anything about it, in beta 20 we replaced the underlying layer of the iOS-SDK and some of the slowness might be due to that change (it is designed a bit differently).

With that said we will look into some things that might improve the performance.

**Comment by NOlivNeto** [comment] 2016-09-12 19:22
The Beta 21 is taking forever to start any track... I'm experiencing about 3 to 10 (!!!) seconds to start any track playback in beta 21

**Comment by NickCJ83** [comment] 2016-09-14 12:45
@erdtman have you guys investigated further?
It does feel ridiculously slow. im getting skips between 2900-4200ms
Your help would be much appreciated

**Comment by erdtman** [comment] 2016-09-15 06:52
I have done some more tests and some initial tweaks, I have not gotten back to the old speed but I manage to get it significantly faster.

=== new
2016-09-14 16:45:40.494 Simple Track Playback[5441:74214] SKIP NEXT
2016-09-14 16:45:40.653 Simple Track Playback[5441:74214] SKIP DONE
653-494=159 

2016-09-15 08:36:25. 025 Simple Track Playback[10651:191016] SKIP NEXT
2016-09-15 08:36:25. 183 Simple Track Playback[10651:191016] SKIP DONE
183-025=158

2016-09-15 08:37:29. 371 Simple Track Playback[10651:191016] SKIP NEXT
2016-09-15 08:37:29. 519 Simple Track Playback[10651:191016] SKIP DONE
519-371=148

2016-09-15 08:38:27. 486 Simple Track Playback[10651:191016] SKIP NEXT
2016-09-15 08:38:27. 606 Simple Track Playback[10651:191016] SKIP DONE
606-486=120
(159+158+148+120)/4=146,25

=== old
2016-09-14 16:49:08. 090 Simple Track Playback[5594:77440] SKIP NEXT
2016-09-14 16:49:08. 529 Simple Track Playback[5594:77440] SKIP DONE
529-090=439

2016-09-15 08:32:01. 147 Simple Track Playback[5838:91841] SKIP NEXT
2016-09-15 08:32:01. 729 Simple Track Playback[5838:91841] SKIP DONE
729-147=582

2016-09-15 08:33:05. 722 Simple Track Playback[5838:91841] SKIP NEXT
2016-09-15 08:33:06. 134 Simple Track Playback[5838:91841] SKIP DONE
1134-722=412

2016-09-15 08:34:31. 542 Simple Track Playback[5838:91841] SKIP NEXT
2016-09-15 08:34:31. 991 Simple Track Playback[5838:91841] SKIP DONE
991-542=449

(439+582+412+449)/4=470,5

146,25/470,5 = 30%
70% speed increase

There are some more things we can do that might improve this, I´ll keep you updated.

**Comment by NickCJ83** [comment] 2016-09-15 07:09
Thanks for that @erdtman thats great to hear. Any idea when this would actually be integrated then?
I'm hesitant to ship my latest update due to the speed right now.  Peeps don't have the patience these days :)

**Comment by NOlivNeto** [comment] 2016-09-15 12:18
Thanks, @erdtman. Now it's better. Any idea when is this coming out?

**Comment by erdtman** [comment] 2016-09-15 15:31
We are aiming for a release next week

**Comment by CVertex** [comment] 2016-09-19 11:46
@erdtman Thanks for the update. I look forward to the improved performance 😄

**Comment by volksport** [comment] 2016-09-21 14:48
@erdtman Any chance that release will be today? :D

**Comment by erdtman** [comment] 2016-09-23 11:26
Beta 22 has now been released, please verify if the performance improvement improves your use case too.

**Comment by mhuusko5** [comment] 2016-09-23 13:06
@erdtman is there going to be a proper release/archive, or at least tag, for beta 22?

**Comment by erdtman** [comment] 2016-09-23 13:08
@mhuusko5 yes

**Comment by GabeJacobs** [comment] 2016-09-23 14:19
@erdtman any chance you could write out the changelog like the other releases?

**Comment by erdtman** [comment] 2016-09-23 14:38
@GabeJacobs have a look now

**Comment by CVertex** [comment] 2016-09-25 12:42
@erdtman Thanks for doing this!! This is a big improvement 😸 

I'll continue testing, but it's looking like a big step forward

**Comment by erdtman** [comment] 2016-09-26 10:21
Thanks for the feedback, we will do one more thing that might improve this further, but it also comes down to some changes in the underlying library so we will not get down to the old levels.

As this seem to have improved the situation I will close this issue and if you have further problems please open a new issue (or reopen this one).

**Closed by erdtman** 2016-09-26 10:21 UTC
