### ISSUE TITLE
Seek 20-25x slower in Beta 21 

### ISSUE THREAD

**Issue by gchilds** [spotify/ios-sdk#750] opened 2016-09-09 08:25 UTC
I'm seeing 600-1000ms seek times with Beta 21 as compared to 30-40ms seeks in Beta 17.

This is the difference between seeks feeling "instantaneous" and "slow" to our users.

**Comment by CVertex** [comment] 2016-09-14 08:32
@erdtman Have you had a chance to look at this? Perhaps this is related to https://github.com/spotify/ios-sdk/issues/746 ?

**Comment by erdtman** [comment] 2016-09-15 06:55
Correct it might be related to #746 but it could also be related to some bad usage of the cache, we have seen that it saves data but does not always use the saved data.

**Comment by CVertex** [comment] 2016-09-19 12:14
@erdtman On your investigations, did you uncover the source of this issue?

**Comment by erdtman** [comment] 2016-09-20 05:05
We have not gone into depth on this issue and it is not obvious that my change for #746 will help.

So no I would not say that we have uncovered the root cause of this issue.

**Comment by erdtman** [comment] 2016-09-23 11:27
Beta 22 has now been released, I think it might be a long shot to think that it will have great effect on this issue but please verify.

**Comment by CVertex** [comment] 2016-09-25 12:40
Thanks @erdtman !!! 😄  Seek feels much much better now 😃 

After caching was turned on, perhaps caching had something to do with it? We previously had caching switched off as it was buggy.

**Comment by erdtman** [comment] 2016-09-26 10:18
My guess is that it had to do with caching. I will close this issue for now, we will make some more changes that might improve this further but it is not at all obvious.

If you have further problems please reopen this issue or open e new one.

**Closed by erdtman** 2016-09-26 10:18 UTC
