### ISSUE TITLE
Spotify app v8.5.22: appRemote connects, but delegate methods not called, also appRemote.playerAPI = nil

### ISSUE THREAD

**Issue by rugoso** [spotify/ios-sdk#150] opened 2019-09-12 02:57 UTC
Please can anyone confirm that they can consistently receive calls to the delegate method **appRemoteDidEstablishConnection** after connecting with appRemote with the Spotify app v8.5.22 ??

Or confirm that they consistently can't, like it is my case.

Sometimes (rarely) **appRemoteDidEstablishConnection** gets called, but then the next time I run the app, it does not anymore.

Spotify app v8.5.22 seems to have broken something in the iOS Spotify SDK/API

This happens on my app and also on the latest NowPlayingView app from the demo projects.

Here’s my experience:

Noticed my app didn’t connect to the Spotify app on my iPhone.

Noticed the Spotify app got updated to v8.5.22 on my iPhone.

Tried to run my app on my iPad, it did connect.

Noticed that the Spotify app on my iPad had not been updated yet. 

Updated the Spotify app on my iPad to version 8.5.22.

Now my app doesn't connect to the Spotify app on my iPad.

Spend the next 4 hours trying to find the bug. Can’t know exactly what’s happening but these are my findings so far:

The appRemote seem to connect, it logs **AppRemote: Established a connection to the Spotify app.**

But the delegate methods don’t get called: **appRemoteDidEstablishConnection didFailConnectionAttemptWithError didDisconnectWithError**,  none of those methods ever get called.

Also, even after appRemote.isConnected returns true, **appRemote.playerAPI appRemote.userAPI appRemote.imageAPI appRemote.contentAPI**, all of those equal nil

Also tried to call appRemote.disconnect(), then appRemote.connect(), same situation

I’m running the latest NowPlayingView project with the latest SDK (just downloaded it a few hours ago), running iOS 12.4.1

Other users seem to have encountered the same problem: issues #149 (now closed but not solved) and #114 (down to the most recent comments).

Thanks for reading this long post!

**Comment by WickedChicken42** [comment] 2019-09-12 03:01
As the author of #149 I had closed it as a Dupe to #114.

**Comment by haikusw** [comment] 2019-09-12 03:16
This is a more detailed duplicate of #114 so with a better title.

Seeing this here also. 

The following all done with this environment:
    Xcode 11.0 GM, macOS 10.14.6, iOS 12.3.1 with latest Spotify iOS app (v8.5.22.739)
though tested with Xcode 10.3 and verified same thing there.

Note that successful connection only seems to happens if:
1. both apps are quit (Spotify and NowPlayingView app)
2. Spotify is launched first AND a track is played.
3. but the `appRemoteDidEstablishConnection` does not get called.

(which seems like a bug all by itself; shouldn't require launching OR starting a track playing).

If for step 2 above you just launch Spotify but do not start a track playing, then error messages like the following are emitted:

> 2019-09-11 20:05:44.412118-0700 NowPlayingView[7517:3551919] AppRemote: Connecting...
> 2019-09-11 20:05:44.433569-0700 NowPlayingView[7517:3552135] [] nw_socket_handle_socket_event [C1.1:1] Socket SO_ERROR [61: Connection refused]
> 2019-09-11 20:05:44.436617-0700 NowPlayingView[7517:3552135] [] nw_socket_handle_socket_event [C1.2:1] Socket SO_ERROR [61: Connection refused]
> 2019-09-11 20:05:44.437811-0700 NowPlayingView[7517:3552147] [] nw_connection_get_connected_socket [C1] Client called nw_connection_get_connected_socket on unconnected nw_connection
> 2019-09-11 20:05:44.437901-0700 NowPlayingView[7517:3552147] TCP Conn 0x2805c0480 Failed : error 0:61 [61]
> 2019-09-11 20:05:44.441258-0700 NowPlayingView[7517:3551919] AppRemote: Failed connection attempt with error: Error Domain=com.spotify.app-remote.transport Code=-2000 "Stream error." UserInfo={NSLocalizedDescription=Stream error., NSUnderlyingError=0x283e9aa00 {Error Domain=NSPOSIXErrorDomain Code=61 "Connection refused" UserInfo={_kCFStreamErrorCodeKey=61, _kCFStreamErrorDomainKey=1}}, NSLocalizedRecoverySuggestion=Reconnect the transport to the Spotify app., NSLocalizedFailureReason=A stream error has occured in the transport.}
> didFailConnectionAttemptWithError

Notice that last line.  The delegate method `appRemote(_ appRemote: SPTAppRemote, didFailConnectionAttemptWithError error: Error?)` *IS* called in this case.

----

So tried again to do the three steps and this time got the following:

> 2019-09-11 20:07:25.701036-0700 NowPlayingView[7519:3552985] AppRemote: Connecting...
> 2019-09-11 20:07:25.730507-0700 NowPlayingView[7519:3552985] AppRemote: Established a connection to the Spotify app.
> 2019-09-11 20:07:25.735329-0700 NowPlayingView[7519:3552985] AppRemote: Failed to authenticate with the Spotify app.
> 2019-09-11 20:07:25.735771-0700 NowPlayingView[7519:3552985] AppRemote: Failed to establish a sesssion with error: Error Domain=com.spotify.app-remote.wamp-client Code=-1001 "wamp.error.authorization_failed" UserInfo={details={
    message = "No token provided.";
}, NSLocalizedFailureReason=wamp.error.authorization_failed}
> *** didFailConnectionAttemptWithError
> 2019-09-11 20:07:38.516348-0700 NowPlayingView[7519:3552985] AppRemote: Disconnected with error: (null)

So got a different error this time with the app playing.  I may have rushed the launch of the NowPlayingView app and the track might have just been starting still, maybe.

Not sure why there's a token issue because the ReadMe for this Demo app says no token exchange exchange/swap needed...

>This Swift project focuses on how to interact with the Spotify client to control playback, subscribe to player state changes, fetch content, and more. This project does not require you to have a server for token swaps so you can ignore the provided ruby script. You will have to run this project on a real device as it requires the Spotify iOS app to be installed.

----

Third time, being careful not to rush starting NowPlayingView demo app, and I get what seems like the behavior we've all been seeing if we follow those steps carefully:

appRemote connection established message but no appRemoteDidEstablishConnection(_ appRemote: SPTAppRemote)` delegate call being made.

> 2019-09-11 20:08:42.388104-0700 NowPlayingView[7523:3553838] AppRemote: Connecting...
> 2019-09-11 20:08:42.414365-0700 NowPlayingView[7523:3553838] AppRemote: Established a connection to the Spotify app.
 

Now those steps shouldn't be required so that's a related issue it seems like.

**Comment by rugoso** [comment] 2019-09-12 04:30
Found an iPad mini with an older version of Spotify (8.5.1 from last April), did run the newest NowPlayingView project ... it works every single time.

With this older Spotify version (8.5.1), if I close both apps, then open NowPlayingView, and from there launch Spotify, it works, it connects and shows what song is playing from the NowPlayingView app ... I can close both apps and repeat the same process, and it works always (did this at least 10 times)

On the other side, I've found that sometimes if I don't use the most recent Spotify app (8.5.22) for a while, then open it from the NowPlayingView app, it connects the first time ... but if I close BOTH apps, then the next time I launch Spotify from the NowPlayingView ... it launches the Spotify app, but it no longer connects (the circle turns orange but not green), no matter how many times I try, it just won't connect again.

Hope this helps reproduce the problem on the side of the developers of the Spotify app.

Cheers!

**Comment by haikusw** [comment] 2019-09-12 04:40
Nice work.  I wonder if there's any relation to whatever broke in the latest Spotify iOS app that is causing this: https://github.com/spotify/ios-sdk/issues/146 ?

**Comment by haikusw** [comment] 2019-09-12 04:40
Oh, I can confirm that `appRemote.playerAPI == nil` here also.

**Comment by rugoso** [comment] 2019-09-12 05:11
i did this

```
func appRemoteDidEstablishConnection(_ appRemote: SPTAppRemote) {
	print("didEstablishConnection", self.appRemote, appRemote, self.appRemote === appRemote, self.appRemote.playerAPI!)
        self.appRemote = appRemote
        playerViewController.appRemoteConnected()
    }
```

and the result of print was

`didEstablishConnection <SPTAppRemote: 0x2801b50e0> <SPTAppRemote: 0x2801b50e0> true <SPTAppRemotePlayerAPIImplemenation: 0x2822b3c80>`

which shows that appRemote is the same object (the instance variable value and the passed argument are the same, the update doesn't do anything)

**Comment by haikusw** [comment] 2019-09-12 05:14
Thanks. That's what I expected but good to have it confirmed.

**Comment by kkarayannis** [comment] 2019-09-12 07:50
Hi everyone! I can confirm that there was a regression in the Spotify app in a recent release that prevents App Remote from connecting. This is known and there's already a fix internally which will be released in an upcoming release.

In the meantime, there is a workaround to help you with your testing. The issue only happens when the Spotify app first launches (ie it's not suspended in the background). So you can:
- Launch Spotify
- Suspend it (exit to the iPhone/iPad home screen)
- Open Spotify again. No need to start playback.
- Launch your app and connect with App Remote.

I know it's a clumsy workaround and that you can't really tell your users to do it, but it might help with your development and testing.

Thank you very much for your patience on this issue.

**Comment by WickedChicken42** [comment] 2019-09-13 13:51
Got all excited but the new 8.5.23 doesn’t have the fix :(

**Comment by williamrct** [comment] 2019-09-13 14:23
I am an IOS developer is there early access for releases? Is there eta for the v8.5.24 release? Thanks

**Comment by kkarayannis** [comment] 2019-09-16 14:21
@williamrct There's a beta program but our TestFlight slots are currently full: https://community.spotify.com/t5/Spotify-Answers/How-do-I-become-a-Spotify-Beta-tester/ta-p/4551518
I'll see if we can get a few new slots.

If there are no complications, I estimate the release be out towards the end of this week or the beginning of the next week.

**Comment by eanntuan** [comment] 2019-09-16 14:46
Does anyone know if there is a dev workaround for this issue? Rather than having users follow the workaround listed above (kill both apps, open spotify, open your app, play music)?

**Comment by yuyangchee98** [comment] 2019-09-20 23:26
Will the update affect ios 13 users?

**Comment by samgold89** [comment] 2019-09-23 23:20
Any updates here?

**Comment by williamrct** [comment] 2019-09-24 00:51
Kostas

Thank you... I’ve been trying since you sent me the link but no luck yet with joining.  

William

**Comment by kjanjuha** [comment] 2019-09-24 10:21
Seem to also be getting the same issue. I can't play a track through the SDK at all. The only time it works is on the first-time opening the Spotify app.

**Comment by kkarayannis** [comment] 2019-09-24 13:11
Unfortunately the latest release has been delayed due to a bug that was discovered. Look for the release with the fix next week.

**Comment by kjanjuha** [comment] 2019-09-24 13:26
Thanks for keeping us updated. Really appreciate that!

**Comment by pedro** [comment] 2019-09-24 16:31
Right on, thanks for the updates folks!

I'm sure this was considered already, but is there a chance Spotify would just roll back the release that introduced this bug? Rerelease 8.5.21 so things work while 8.5.24 is tested.

Thanks,

**Comment by kkarayannis** [comment] 2019-09-24 16:38
While that would be a useful option to have, the App Store sadly doesn’t give developers that option.

**Comment by pedro** [comment] 2019-09-24 16:47
I've done it before, just push old release with a new build/version?
To fix my comment above – rerelease 8.5.21 as 8.5.24 or .25, then current .24 becomes .26.

**Comment by williamrct** [comment] 2019-09-27 11:53
Just installed the latest update ETA 5.25 and still seeing the same issue. Can you please advise as to whether or not this current update was to fix the issue.

William

**Comment by kkarayannis** [comment] 2019-09-27 12:51
Yes 8.5.25 should fix issue. It's weird that it's still happening for you. Are we talking about the same issue? Did the previous workaround work for you?

**Comment by williamrct** [comment] 2019-09-27 13:11
Yes the previous work around did work.

After some additional testing we are noticing it is a timing issue and it occurs intermittently. 

I am gathering specifics on it and will share once I have additional meaningful data.  

William

**Comment by WickedChicken42** [comment] 2019-09-27 14:58
I pulled down v8.5.25 and things are happy again for my app.  I'll be interested to see what is happening to williamrct.

**Comment by kjanjuha** [comment] 2019-09-27 15:33
v8.5.25 solved the issue

**Comment by NathanWalker** [comment] 2019-09-27 17:04
@kkarayannis Is there a regression or change with Free account vs. Premium in the latest v8.5.25?
Previously you could play a specific track id (free or premium) however now it seems playing a track id with a free account seems to play a totally different track vs the same id request to play under premium? Possible that the track id's are strangely different under free account vs. premium?

**Comment by pedro** [comment] 2019-09-27 18:05
Yes! Looking good here too, thank you folks.

**Comment by kkarayannis** [comment] 2019-09-27 18:25
I’m happy to hear the update has fixed the issue for most people. I’m curious about any remaining issues. It might be something else we need to look at.

**Comment by rugoso** [comment] 2019-09-27 22:05
@williamrct 

Don't know if this is the issue you are experiencing but I recommend you check your version inside the Spotify app itself (Settings -> About), cuz the App Store told me I had updated the app and for whatever reason it kept the previous one.

I had to update the Spotify app like 3 times until it actually showed me the right version inside the Spotify App.

The version that I see now is 8.5.25.760, which is working just fine now with the NowPlaying demo project :)

Thanks for the update!

**Comment by kkarayannis** [comment] 2019-09-30 11:20
Version 8.5.25 should now be rolled out to everyone. Since the fix seems to work for most people I'll close this issue for now. If there's another problem, please open a new issue.

**Closed by kkarayannis** 2019-09-30 11:20 UTC

**Comment by LuisMendez01** [comment] 2020-05-14 17:25
> v8.5.25 solved the issue

HI kjanjuha,

How did you get to play songs ? I basically have a tableView of URIs when I press on any cell I want to start playing the specific song based on the URI given to this cell, how did you get it to work ? I can't get it to play, it only plays one song when I connect my app to the spotify app
