### ISSUE TITLE
Application Authentication returns "unknown error" when Spotify is closed

### ISSUE THREAD

**Issue by GabeJacobs** [spotify/ios-sdk#505] opened 2015-12-08 16:00 UTC
When the Spotify iOS app is closed, and I try to authenticate without our app (on beta 13), I recieve the error:

    Error Domain=com.spotify.auth Code=0 "unknown_error" UserInfo=  {NSLocalizedDescription=unknown_error}

If the Spotify App is open, and I try to authenticate, it works.

**Comment by GabeJacobs** [comment] 2015-12-08 17:38
@JMSerruya are you guys aware of this issue?

**Comment by JMSerruya** [comment] 2015-12-09 12:49
Hi Gabe. 

Thanks for reporting, we will take a look at this internally and prioritize it.

**Comment by GabeJacobs** [comment] 2015-12-11 16:10
@JMSerruya No problem, thanks for checking it out.

**Comment by GabeJacobs** [comment] 2015-12-11 16:23
@JMSerruya but still happening on beta 14 FYI

**Comment by GabeJacobs** [comment] 2015-12-17 17:13
Would it be safe to go back to beta-12. There doesn't seem to be a way around this issue on the last two builds.

**Comment by GabeJacobs** [comment] 2015-12-17 17:20
It mostly is an issue when on LTE and not Wifi. Often times also the app hangs when it gets to the Spotify and will only return to our app after 5-10 seconds. We've reverted back to beta-12 for the time being. I think this should be priority 0 though since having to login with your username and password even if you are logged into the Spotify app is pain. I hate to bring up a competitor, but the way Spotify does it is wonderful. Credentials are stored in the keychain and you are only logged out if you wipe your keychain. For a user, this is the way to go.

**Comment by argon** [comment] 2015-12-18 14:12
This has to be a problem with the Spotify App. I have tried sending the login URL that would be generated by the SDK without using any of the SDK and it just returns most of the time. Occasionally it will succeed but it seems to be less frequent nowadays. Going to have to revert to an older version for now.

```
<redirect_uri>?error=unknown_error&error_description=Error%20Domain%3Dcom.spotify.hermes%20Code%3D126%20%22(null)%22
```

**Comment by zenangst** [comment] 2015-12-22 18:43
I'm getting the same response as @argon

**Comment by michalumni** [comment] 2015-12-23 01:26
Found the same issue on beta 14...

**Comment by JMSerruya** [comment] 2015-12-23 01:27
Thanks everyone. This is currently being looked at, the fix will be included in our next release!

**Comment by 909kishore** [comment] 2016-01-12 15:17
Any idea when that next release may come out?  We're looking forward to in-app authentication

**Comment by JMSerruya** [comment] 2016-01-27 19:48
@909kishore @michalumni @GabeJacobs 

Can you please test this again against the Spotify iOS 4.8 Client that has just been released to the appStore?

**Comment by JMSerruya** [comment] 2016-01-27 19:48
@argon @zenangst ^

**Comment by GabeJacobs** [comment] 2016-01-27 19:50
@JMSerruya I'll get back to you either tonight or tomorrow. Any chance the handoff issue was fixed too? Or is that related to the sdk only

**Comment by JMSerruya** [comment] 2016-01-27 19:55
@GabeJacobs that's not addressed but this app update, that is a fix contained by the embedded library that manages playback that is used by the mobile SDK. 
We are doing internal testing for it and will release when ready!

**Comment by 909kishore** [comment] 2016-01-28 16:18
@jmserruya we're having issues setting this up.  Can the example project in the sdk be updated for this new auth and/or can you point me in the direction of a sample project that uses the new auth?

**Comment by GabeJacobs** [comment] 2016-01-29 20:22
@JMSerruya this seems to work now

**Comment by GabeJacobs** [comment] 2016-01-29 20:23
@JMSerruya But only since the most recent Spotify release right? I wonder if we should assume most Spotify users have auto-update on

**Comment by JMSerruya** [comment] 2016-01-30 10:02
@GabeJacobs that is correct!

I'm going to close this issue now since it is resolved.

@909kishore : did u added the spotify-action uri to your plist?
Open another ticket with your plist and i can take a look at it, feel free to tag me.

**Closed by JMSerruya** 2016-01-30 10:02 UTC

**Comment by GabeJacobs** [comment] 2016-02-01 16:57
@JMSerruya just got it again :(

"2016-02-01 11:54:40.731 Cymbal[470:114878] Error Domain=com.spotify.auth Code=0 "unknown_error" UserInfo={NSLocalizedDescription=unknown_error}"

**Comment by bassntweeter** [comment] 2016-02-02 05:30
@gabejacobs when did it happen? Do you have a way to reproduce it?

**Comment by GabeJacobs** [comment] 2016-02-02 15:36
@bassntweeter I will try today. However I remember having trouble reproducing, but every 5 or so times I would try the error would occur.

**Comment by GabeJacobs** [comment] 2016-02-02 21:10
@bassntweeter @JMSerruya I have it in a state where everytime I try it it returns the error, Is there anything I should inspect?

I printed out the URL that spotify is returning and it seems to be as follows

`anthem-login://callback?error=unknown_error&error_description=Error%20Domain%3Dcom.spotify.hermes%20Code%3D126%20%22(null)%22`

Also the current state of the Spotify app is in the search mode (search results are show as well).

Does this help in anyway?

**Comment by bassntweeter** [comment] 2016-02-03 15:11
@gabejacobs thanks! I did not have time to go into this today. Is the state reproducible? I.e. Can you guide us in how to reproduce it?

**Comment by GabeJacobs** [comment] 2016-02-03 18:45
@bassntweeter Having trouble finding steps to reproduce? Are you not able to see the error?

**Comment by kocyigityunus** [comment] 2016-02-05 13:32
i can reproduce this error anytime i want. 

just add 

```
<key>LSApplicationQueriesSchemes</key>
	<array>
        <string>spotify-action</string>
	</array>
```

to yout info.plist. And try to call

```
[[SPTAuth defaultInstance] handleAuthCallbackWithTriggeredAuthURL:url callback:^(NSError *error, SPTSession *session) {
                // the error will be "unkown error"
            }];
```

i am on a new ipad with ios 9.1 (13B143) and spotify version  :4.8.0.1085

**Comment by bassntweeter** [comment] 2016-02-11 14:41
@GabeJacobs Thanks for helping out in such an extensive way, alas I have found no reliable way of reproducing this unfortunately. The error you got is the Spotify app saying that it has no connection to the Spotify backend when trying to authenticate. I guess this could happen if you have network when starting the authentication, and then loose network in the middle of the process.
@kocyigityunus What does your error description say?

**Comment by cjhanson** [comment] 2016-02-24 19:16
We are seeing this same issue. The first time our app tries to get a session the spotify app launches, then returns to our app with the unknown_error. If you manually go to spotify, start/stop playback of a track, then try auth from our app the issue goes away.

**Comment by dnosk** [comment] 2016-03-04 05:07
Referencing https://github.com/spotify/ios-sdk/issues/616 I found a way to always reproduce this. When one of my users with the name of Hérmes tries to use the auth, this error occurs. Not just for her, but everyone after she attempts. Hopefully this helps.

**Comment by nathanandersen** [comment] 2016-03-28 01:01
I'm still getting this error.

Every time that I try to login, the spotify app opens, and then login fails.

**Comment by epatel** [comment] 2016-03-29 20:43
Getting the same...

`precious-login://callback?error=unknown_error&error_description=Error%20Domain%3Dcom.spotify.hermes%20Code%3D126%20%22(null)%22`

What can `Code=126 "(null)"` be about?

**Comment by staminajim** [comment] 2016-04-07 13:44
Chiming in that I'm getting this also with the latest SDK and version of the Spotify iOS app:

```
seatgeek://spotify-auth?error=unknown_error&error_description=Error%20Domain%3Dcom.spotify.hermes%20Code%3D126%20%22(null)%22
```

Using web auth succeeds.

**Comment by staminajim** [comment] 2016-04-07 14:36
This seems to be a reliable way to reproduce:
  * Authorise your app using the native Spotify app auth
  * Delete your app, and reinstall
  * Trigger a spotify auth again.

The spotify app opens, then returns immediately with the above error.

**Comment by GabeJacobs** [comment] 2016-04-07 16:16
@staminajim I've reverted to beta 12 which always uses the webview. This is better than getting the error ¯\_(ツ)_/¯

**Comment by staminajim** [comment] 2016-04-07 16:21
If I kill the Spotify app, and then redo the process the native Spotify app auth works, so maybe there's a clue in there somewhere.

**Comment by brki** [comment] 2016-04-09 16:07
For my part, I've noticed that if I open the Spotify app and start streaming a song and then pause the playback, and then go back to my app and re-try authorization, it works.

**Comment by michaelmerrill** [comment] 2016-04-21 06:43
I'm also receiving the `error=unknown_error&error_description=Error%20Domain%3Dcom.spotify.hermes%20Code%3D126%20%22(null)%22` error. I can bypass the error if I terminate the Spotify app and re-login on my app. Could we reopen this issue?

**Comment by samgiagtzoglou** [comment] 2016-04-30 21:51
Also having this issue

**Comment by nathanandersen** [comment] 2016-05-02 04:48
I had this issue but it has since been resolved: make sure that you have entered your bundle ID on `developer.spotify.com`.

**Comment by helkarli** [comment] 2016-07-19 07:31
I had different redirect URLs in the app and on developer.spotify.com. Make them matching and don't forget to press the SAVE button at the end of the page. That did the trick for me.

**Comment by GabeJacobs** [comment] 2016-07-19 18:38
@nathanandersen did this and still getting the error :(

**Comment by IsaiahJTurner** [comment] 2016-08-07 03:18
+ experiencing this as well. why was this closed?

**Comment by adamontherun** [comment] 2016-08-21 00:15
@JMSerruya I'm seeing this issue about 1 in 3 times when authenticating. This is preventing launch to the app store. Any updates on your end? thanks!
