### ISSUE TITLE
SPTAuthViewController login failed + delegate issues

### ISSUE THREAD

**Issue by bensebborn** [spotify/ios-sdk#756] opened 2016-09-18 09:25 UTC
Hi

I am using the latest SDK, and have implemented SPTAuthViewController as follows:

```
    -(void)authenticateWithSpotify{
    NSLog(@"authenticateWithSpotify");

    SPTAuth *auth = [SPTAuth defaultInstance];
    
    auth.allowNativeLogin = YES;  
    auth.requestedScopes = @[SPTAuthUserLibraryReadScope];
    
    SPTAuthViewController *spotifyAuthViewController = [SPTAuthViewController authenticationViewControllerWithAuth:auth];
   
    spotifyAuthViewController.delegate = self;
    spotifyAuthViewController.hideSignup = YES;
    spotifyAuthViewController.modalPresentationStyle = UIModalPresentationOverCurrentContext;
    spotifyAuthViewController.modalTransitionStyle = UIModalTransitionStyleCrossDissolve;
    
    self.modalPresentationStyle = UIModalPresentationCurrentContext;
    self.definesPresentationContext = YES;
    [self presentViewController:spotifyAuthViewController animated:NO completion:nil];

 
}
```

when I call this, the following happens:

1) 1st call allows me to login, window closes, but then the following is logged in the console:

`*** Auth error: Error Domain=com.spotify.auth Code=0 "unknown_error" UserInfo={NSLocalizedDescription=unknown_error}`

2) No delegate methods are called

3) If I try again, our code recognises a valid session immediately and continues the flow.

It seems as though the SDK is reporting a failed login, but then doesn't call any delegate method.

See my implementation:

```
-(void)login{

 [[SPTAuth defaultInstance] setClientID:kClientId];
    [[SPTAuth defaultInstance] setRedirectURL:[NSURL URLWithString:kCallbackURL]];
    [[SPTAuth defaultInstance] setSessionUserDefaultsKey:  kSpotifyDefaultSessionKey];
    
    SPTAuth *auth = [SPTAuth defaultInstance];


 if (auth.session == nil) {
        
        //Never logged in
        NSLog(@"Nil session");
        [self authenticateWithSpotify];
        return;
        
    }

    if ([auth.session isValid]  && [auth.requestedScopes containsObject:SPTAuthUserLibraryReadScope]) {
        
        //Valid session, continue
        NSLog(@"Valid session with correct perms");
        //Do Stuff
        return;
    }
   
    if (auth.session && auth.hasTokenRefreshService) {
         
         NSLog(@"Old session");
         [self reAuthenticateWithSpotify];
         return;
        
         //Had a session but it's expired, so need to refresh token
     }
    
    [self authenticateWithSpotify];
}


- (void) authenticationViewController:(SPTAuthViewController *)authenticationViewController didLoginWithSession:(SPTSession *)session{
     NSLog(@"didLogin");
    self.session = session;
    //Do import
    NSLog(@"Ready to import");
    [self importSpotifyArtists];
}

/**
 An error occured while logging in
 
 @param authenticationViewController The view controller.
 @param error The error (Note that the session object in the `SPTAuth` object passed upon initialization
	is cleared.)
 */
- (void) authenticationViewController:(SPTAuthViewController *)authenticationViewController didFailToLogin:(NSError *)error{
    NSLog(@"didFailToLogin");
    [Utilities showAlertWithTitle:@"Spotify Login Error" message:[error localizedDescription]];
}

/**
 User closed the login dialog.
 @param authenticationViewController The view controller.
 */
- (void) authenticationViewControllerDidCancelLogin:(SPTAuthViewController *)authenticationViewController{
    NSLog(@"didCancelLogin");
    return;
}
```

However, even though it reports a failed login, when I go through this flow again, I Immediately get:

`Valid session with correct perms`

How do I recognise the valid session from the first click immediately?

**Comment by erdtman** [comment] 2016-09-19 12:56
Could you have a look at #650 to see if that issue matches your problem too.

if it does please close this one as duplicate.

**Comment by skiddle** [comment] 2016-09-19 13:20
The initial login issue is a duplicate of #650.

I notice that the delegate methods never call though so presume this a seperate issue.

I've seen in the example project, there is a notification which calls the delegate methods, which seems strange (why have delegate methods?)

eg

```
[[NSNotificationCenter defaultCenter] postNotificationName:@"spotifySessionUpdated" object:nil];

...

-(void)spotifySessionUpdatedNotification{
    
   
    SPTAuth *auth = [SPTAuth defaultInstance];
    if (auth.session && [auth.session isValid]) {
        [self authenticationViewController:self.spotifyAuthViewController didLoginWithSession:auth.session];
    } else {
        [self authenticationViewController:self.spotifyAuthViewController didFailToLogin:nil];
    }

}
```


I would have thought the STPAuthViewController would call those delegate methods itself rather than us having to do it?

**Comment by matijse** [comment] 2016-09-19 18:23
I use `auth.allowNativeLogin = NO;`. That way you always use the AuthenticationViewController (Webview popup) and never go to the Spotify app for authentication. Downside is that users need to enter their password, but its a work around for the `unknown_error` bug...

As I understand the AuthenticationViewController uses the delegate methods. When you go to the Spotify app and return, this is done via an "url", which is handled in the `AppDelegate`...

**Comment by bensebborn** [comment] 2016-09-20 06:14
This works much better turning native flow off.

**Comment by erdtman** [comment] 2016-09-20 06:17
does this mean that your remaining issues are the same as in #650, i.e. can we close this issue?

**Closed** 2016-09-20 06:22 UTC

**Comment by khay4icloud** [comment] 2017-08-05 20:55
I am facing the same as above not able to call the delegate methods, hence I followed the above mentioned solution and now Xcode throws an error the auth.allowNativeLogin = NO not found.
Any help is appreciated. Thanks
