### ISSUE TITLE
Crash on iOS 7

### ISSUE THREAD

**Issue by Anders27** [spotify/ios-sdk#231] opened 2015-01-28 16:08 UTC
2015-01-28 17:03:28.727 myApp[434:217] -[NSNull longValue]: unrecognized selector sent to instance 0x3846ca70
2015-01-28 17:03:28.743 myApp[434:217] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull longValue]: unrecognized selector sent to instance 0x3846ca70'
*** First throw call stack:
(0x2d4e5f83 0x37c96ccf 0x2d4e9917 0x2d4e8203 0x2d437768 0x176fc1 0x189807 0x1895a1 0x184b27 0x3817e833 0x38191921 0x38191b21 0x382c0bd3 0x382c0a98)
libc++abi.dylib: terminating with uncaught exception of type NSException

![screen shot 2015-01-28 at 17 03 35](https://cloud.githubusercontent.com/assets/10338608/5941281/3c413316-a710-11e4-9e74-b1c8eb36c038.png)

**Comment by iKenndac** [comment] 2015-01-28 16:10
Duplicate of #219.

**Closed by iKenndac** 2015-01-28 16:10 UTC
